### ISSUE TITLE
please, update this repo with your files from mega.nz

### ISSUE THREAD

**Issue by meleu** [UDb23/rpie-custom#2]
Hey bro!

In the forums you said:
> Complete migration will take some time as I'm also rechecking/improving while moving.

What do you think about doing a complete migration putting the "unchecked/unimproved" files in a dir, let's say `oldfiles`? And then you can do your rechecking/improvements while moving from `oldfiles` to a more appropriated directory.

I really would love to get your art from command line :-)

If you are busy, I can submit a PR with all those `oldfiles` from mega.nz

Thanks for all dude!

**Comment by UDb23** [comment]
I'll move all files to the repo using current folder structure.
Then I'll create a "WIP" (work in progress) folder to play with updated/newer versions of the logos. These  "improved" ones will be moved to regular folders when I'm satisfied with 'em.

**Comment by UDb23** [comment]
Done. All files from MEGA now here.

**Comment by meleu** [comment]
Thanks man!

Just a note: if I remember right the [Game Cube logo with white letters](https://github.com/UDb23/rpie-custom/blob/master/more/gamecube%20white.svg) was made for the Carbon theme, because the black letters became invisible on Carbon. I already submitted this file to the official Carbon theme repo and it was merged [as you can see here](https://github.com/RetroPie/es-theme-carbon/blob/master/gc/art/system2.svg). Maybe you can delete the file from your repo here.

**Comment by UDb23** [comment]
Thanks bro!
Didn't notice that; file deleted.
